language: java
script:
- mvn test
- mvn install -DskipTests=true
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: cytC0ZejmXZWIwaSqYnaudFRZ9VPsgdolvsoafUyfpCYhRECcaXwUx0yupxzNq7y4fWe7Eb7hDYqY9S/utBcvtNL32nwI3+dG/3KCq67QGbn98oHJCBsCJjxJR1qo6gDfj1jMJ71NhRm95HD/yAr8o4bojpVLNkoe4gtPylZ9xkP6vqevsL9asLQW18h4pofYo6b87n7dC2GG8bCPH3rXJYppAiayPn3KNAxE9iWgTQCagH+yzgdZk0wm06HvMV7a5IPjXOVC7zRGiyvKlCP+lmTfuD6+e1zKSmwztLu7SXLgEjWkTanHhtRGbpkgIc7qZ7/9jsKIPwwyI0s60g5RbVjgyUNa/tRn8RqJtJxTKEHgaaFgpzEs8XObvNQiSy0ZDtvdlMxHVuXenQBJ4GA4GoTgxcjvm4UpbebmJzjFasihsabt9bZE/N92MhP+WmTy6opbHKT73t7uasa+fRQRh3TKTPQB8TKF6ydOb6pgCOgytptf9+XzsfqKcT5rhqQepuZxB/0a7pwvnoLyjSbCizJaR4t3ottmZHFSGXcg5u4c5JudIhJFCyCt0TK2NwQMGNZq2Q2nPC9jgFkTSI9XSKSdP4lpSHRKmPNITou14L9+gue+BI+ExiJuQuZ91tziSZMqQoi5tkH/n5CY1AjMyVk+aWu72OJaPdKD0siGb8=
after_success:
- mvn clean cobertura:cobertura coveralls:report
