language: java
script:
- mvn test
- mvn install -DskipTests=true
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: BcWJ8qNwwX85I64YfqlQ0i7oFchp1oocengdyrU99rcMr4/YkJwbxyLC6wFb0BMBKuWXIA45vjS44Ot5tvdg/BNSJVFkekazyMA0Uc7LFsj++7CkC+4VBHEhCjbKF1KZYTmNuzFfnibG0hbFI8Jmc5OUXIyhIngKOEtnwN68Qn0FiipVxiyw5+j8EoOeZPVA06pxA6nkT2YkHmqvrhLCV9rVSlwjR5dfU64moirIMxxQZ26qk6LMXDri1dp1VCv/54GyQxP9KiiZOG+7/LSzY9QPDhnEuIrAUlxUurjqup1muP5iRPYlEDYvnBcH7acJyNnwsIDi7joaSP5vLZHhsNw8RoPqamxHfcav/YUKS2Xn85JOeVebli6ZFxQ90AQhaZIu+coIIXcdQ88QB6A9ZFzSwtOmllZE3i+fGJXUsEJok/6k+K/5VGqLH//Rj570TnsKYN30gT14Ws1CWnYOBs9Z9UhArA+OVQMCPHR9b44qK6db//YLq5sYK8QKf4BBJARqdrH/HJQDidHbmlXInwtECyAPXHt+m/HJDyC7WSFC/G9vS5isUgemZT0ukVbgrtArN5+hX9TQFGueojhcPmB0cFd+kztqmRudKpnR8uUZPN8XJbQHJ2QFOYQTsp+OOVzfAEKkPE9T08x8q1bLsabppX7U3NSONgAPQlEZf7Y=
after_success:
- mvn clean cobertura:cobertura coveralls:report
