language: java
script:
- mvn test
- mvn install -DskipTests=true
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: SBpB84XV+ZoZKmAeXVWo2Yr3v+2PVT2C31bcIVrrV/ouKawuRghmOD7L9W1x7WEx+Wr9EiNwUf1sk3iPk3cQdbAKUm97QFgKezgZT778lg1NVfwVPkSeiA92PFUo9NbhonoMu5R6WuKx7R/lJIN/UCB1gMF8Lj7ST3Fm8C3Sl227cpejr3MRGPPjGjudgH4ZVOGSEk1yz3HDjfsHx34bIps/Vzj9PtlYoRktvOp71f9UO/I+oQRvfrkcWWVCCCbt7Urj8dwX3zth3zrWaKeWbaF4TDUXS8LEYbUeaBfUiyP7cFZbMwpxGu3B8zYF9Xfl1YUoHnxm+3A23mdBVkP5KrrMzyvsr/ffq8L3ErvXM7B2DFntDdTEf64odtMDk+aKVOJuH6XZ4QvsOgXMFmdq/dvoIBP6SsZA6exuqm/mcoiLSwSPj/GSlnwF/Z+rNJ06j4Tote2HWIY2tTjelaefjQS1oay1cy7/lTloRcUjk33HRafesnp2XDQiB62jP6Y8gWQwYkkSQu/3vEuxFrLkpw5E4TlqKYQMCWnOkSBZIvnBW9nIMKGA2dizWQiKVOmQ+dHTdfhlJXL2ErsklCj4jvm5Yct46jvAKOp3qwljZtwKyfdNjqrqZfcNJClo85P+WBf7Qo61cY5nBplap0awPVJ9tQJ6xqWGKxiLDxNn/9A=
after_success:
- mvn clean cobertura:cobertura coveralls:report
